package com.managementsystem.Inventory.model;

import jakarta.persistence.*;

@Entity
// Can use lombok for boiler plate code but i did this rather than that
//entity annotation for jpa
//with autogenerated ID
public class Item {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//For fetching details using id of user)
    private Long id;
    @Column(nullable = false)
    private String name;

    private String description;

    private int quantity;

    public Long getId(){
        return id;

    }
    public void setId(Long id){
        this.id = id;

    }
    public String getName(){
        return name;

    }
    public void setName(String name){
        this.name = name;

    }
    public String getDescription(){
        return description;

    }
    public void setDescription(String description){
        this.description = description;

    }
    public int getQuantity(){
        return quantity;

    }
public void setQuantity(int quantity){
        this.quantity = quantity;

}

}
